Update tutorial.rst
removed the period from "tarbell serve." since it causes an error.  See below.

 $ tarbell serve.

Error: Error! Unknown command 'serve.'.